# Simple Project Configuration Template
# Copy this file to config/project.yml and customize for your project
# This is a minimal configuration - phases are optional

project:
  name: "YourProjectName"  # CUSTOMIZE: Your project name
  description: "Brief description of what your project does"  # CUSTOMIZE: Project description
  version: "1.0.0"
  
  # Project paths - CUSTOMIZE these paths for your environment
  workspace_dir: "/path/to/your/project"  # CUSTOMIZE: Absolute path to your project root
  orchestration_dir: "orchestration"  # Usually keep as-is unless you want different structure
  
  # GitHub integration - CUSTOMIZE for your repository
  github:
    owner: "your-github-username"  # CUSTOMIZE: Your GitHub username/org
    repo: "your-repo-name"  # CUSTOMIZE: Your repository name
    project_number: 1  # CUSTOMIZE: Your GitHub project number (from project URL)

# Directory structure (relative to orchestration_dir) - usually keep as-is
directories:
  config: "config"
  scripts: "scripts" 
  agents: "agents"
  memory: "memory"
  logs: "logs"

# Memory files configuration - usually keep as-is
memory_files:
  project_state: "project_state.md"
  task_assignments: "task_assignments.md"
  blockers: "blockers.md"
  decisions: "decisions.md"

# Logging configuration - usually keep as-is
logging:
  orchestrator_log: "orchestrator.log"
  agent_logs_dir: "agents"
  max_log_size: "10MB"
  retention_days: 30

# tmux configuration - usually keep as-is
tmux:
  session_prefix: ""  # No prefix, use full session names
  default_shell: "/bin/bash"
  window_name: "main"
  detach_on_destroy: true

# Integration validation commands (cross-agent) - CUSTOMIZE
integration_validation:
  performance: "your-performance-benchmark-command"
  e2e: "your-e2e-test-command"
  accessibility: "your-accessibility-test-command"
  security: "your-comprehensive-security-scan"

# Phases are OPTIONAL - uncomment and customize if you want project management features
# phases:
#   1:
#     name: "Setup & Foundation"
#     description: "Initial setup and core infrastructure"
#     priority_tasks: [1, 2, 3, 4]  # Your GitHub issue numbers
#   2:
#     name: "Core Development"
#     description: "Main feature development"
#     priority_tasks: [5, 6, 7, 8]